function [ts, ts_data_info] = parse_3dayprog(filepath)
%PARSE_3DAYPROG Parses the 3 day ahead prognosis from a text file
%   The information which is contained in the textfile will be parsed and
%   put into a financial timeseries object.

% last hour in the file to read
end_row=24; % change to 48 or 72 to display more days

%% import the data from the text file by calling the function generated by
% Matlab. Date, hours and quantiles.
[date_list,hours,q2,q5,q12,q25,q37,q62,q75,q87,q95,q97]=parse_3dayprog_gen(filepath,3,end_row+2);

%% check if daylight saving time might cause a problem
if hours(24) ~=24
    display(['Daylight saving time: ',filename]);
end

%% convert the dates and save into fints
dates_help=datestr(datenum(date_list{1},'dd.mm.yyyy'),'yyyy-mm-dd');
dates=datenum([repmat([dates_help,' '],end_row,1),num2str(hours(1:end_row)),repmat(':00:00',end_row,1)]);
ts_data_info={'q2h';'q5';'q12h';'q25';'q37h';'q62h';'q75';'q87h';'q95';'q97h'};
ts=fints(dates,[q2,q5,q12,q25,q37,q62,q75,q87,q95,q97],ts_data_info);
end

